[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, x-sf"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"